### ISSUE TITLE
User Research Plan (preparing Screener Survey and Interview Script

### ISSUE THREAD

**Issue by Hydrophoenix** [zuri-training/chunkfile_team42#1]
The screener survey and interview script will be used to carry out interviews for User Reasearch.
Tools: Google Docs, Google Forms.

**Comment by SahmAdex** [comment]
Done 
Link to the Google Document attached.

https://docs.google.com/document/d/10ksJd-mjreTo3IYvmXOtA5Qj_XTEhzwIc2e1hiX0s5c/edit

**Comment by Momohkay** [comment]
done

https://docs.google.com/document/d/10ksJd-mjreTo3IYvmXOtA5Qj_XTEhzwIc2e1hiX0s5c/edit

**Comment by Richochuko** [comment]
done

https://docs.google.com/document/d/10ksJd-mjreTo3IYvmXOtA5Qj_XTEhzwIc2e1hiX0s5c/edit
