### ISSUE TITLE
Correcting the About page for both the web and mobile responsive screens

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#100]
Designing the web Low-Fi & Hi-Fi designs to match the wireframes already created.
Created the wireframes, Low-Fi, & Hi-Fi designs of the mobile responsive screens of the new About page.

**Comment by FlourishRalph** [comment]
Link to the web Low-Fi design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:3

Link to the web Hi-Fi design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:4

Link to the mobile wireframe design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1965:4962

Link to the mobile Low-Fi design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1885:4501

Link to the mobile Hi-Fi design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1346:4018

**Comment by Neziiii** [comment]
Designed the lo-fi for the web about us page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2074%3A5918

Designed the hi-fi for the web about us page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2078%3A6127
