### ISSUE TITLE
Prototyping of all the Web & Mobile screens

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#102]
Prototyping the web & mobile screens

**Comment by SahmAdex** [comment]
Done.
Link to the Prototype Figma Board Attached.

Web
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2243%3A6440

Mobile
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2264%3A7425

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2243%3A6440

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2264%3A7425
