### ISSUE TITLE
Finishing with the Landing Page

### ISSUE THREAD

**Issue by SahmAdex** [zuri-training/chunkfile_team42#12]
#Landing page completion
Tidying up of the landing page must be completed today

**Comment by FlourishRalph** [comment]
The Low-Fi & Hi-Fi designs of the landing page are completed.
The link to the Low-Fi landing page design
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:3

The link to the Hi-Fi landing page design
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:4

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:4
