### ISSUE TITLE
Enhancement of the designed screens to be moved for development

### ISSUE THREAD

**Issue by SahmAdex** [zuri-training/chunkfile_team42#27]
Tidying up of the designed Hi-Fi screens and movement of those screens to the development page on Figma

**Comment by SahmAdex** [comment]
Done
Link to the Figma Board Attached.

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A4 (Web)
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1346%3A4018 (Mobile)

**Comment by Momohkay** [comment]
done, link attached below

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A4
