### ISSUE TITLE
Interview Implementation

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#39]
The interviews will be carried out for the **User Research**.

**Comment by FlourishRalph** [comment]
The link to the Interview Script;
https://docs.google.com/document/d/10ksJd-mjreTo3IYvmXOtA5Qj_XTEhzwIc2e1hiX0s5c/edit

**Comment by FlourishRalph** [comment]
The link to the interview responses;
https://docs.google.com/document/d/1wCYbiUOw-tl7J-QYcxDLT33N6uhx2QXILpShV-Zi86M/edit

**Comment by Goodnesstaiwo** [comment]
Interview Script;
https://docs.google.com/document/d/10ksJd-mjreTo3IYvmXOtA5Qj_XTEhzwIc2e1hiX0s5c/edit
Interview responses;
https://docs.google.com/document/d/1wCYbiUOw-tl7J-QYcxDLT33N6uhx2QXILpShV-Zi86M/edit

Done

**Comment by Neziiii** [comment]
Carried out an interview with a Data analyst
https://docs.google.com/document/d/1swTuGOnpLGUBRRI9ugpmF0zqj_UEiwvnihVxB6cwaqc/edit?usp=drivesdk
