### ISSUE TITLE
Low-Fi paper sketches

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#40]
Creating Low-Fi paper sketches to help with the creation of screens.

**Comment by FlourishRalph** [comment]
Oyindamola Dosunmu -Landing page & About page
Flourish Ralph & Catherine Ezeobi - Dashboard
Catherine Ezeobi  - Support page
Eluyode Ifeoluwa -Sign up page, Login pages, & Contact Us
Goodness Taiwo -File authentication pages (1-3)
Samuel Adeyinka -My Files and Storage pages
Oko Ukie Emmanuel -Recycle Bin
Oko Ukie Emmanuel & Rebonye Motsweta - Settings page
Omowunmi - Reset password page

**Comment by SahmAdex** [comment]
Done.
The images are attached.
Image 1- My Storage Page
Image 2 - My Files Page

![IMG_20220726_123327](https://user-images.githubusercontent.com/105288886/183665211-1adb94e5-980c-43b7-94ee-e615854ffe00.jpg)
![IMG_20220726_103448](https://user-images.githubusercontent.com/105288886/183665191-69cb9dd2-f1de-46c4-8f88-57133fe6de5f.jpg)

**Comment by FlourishRalph** [comment]
The Chunking Dashboard sketches;

![Image](https://user-images.githubusercontent.com/105368775/183698009-61f4df9b-6b81-4d66-a686-a5b4fbf3c8be.jpeg)
![Image](https://user-images.githubusercontent.com/105368775/183698010-fc9e26d4-0118-4a9f-8874-1ba5fbe07e9a.jpeg)

**Comment by Goodnesstaiwo** [comment]
The authentication pages (1-3)

![20220727_085601.jpg](https://user-images.githubusercontent.com/106138947/183714908-2d535f70-fdad-4a17-a8b0-293fc359f12c.jpg)

![20220727_085626.jpg](https://user-images.githubusercontent.com/106138947/183714996-fd002b7c-d1e7-43b6-991e-615620558246.jpg)

![Uploading z2{3816950} (5e368f32-fe84-4926-a6ea-4370ed2efafd id=0x7f0a03c6 tag=BaseCommentFragment) …]()

**Comment by Eluyodeifeoluwa** [comment]
![IMG_20220723_145543](https://user-images.githubusercontent.com/105178541/183858555-f2629196-8e7b-43d0-9320-c13be83f4ba1.jpg)
![IMG_20220723_145601](https://user-images.githubusercontent.com/105178541/183858594-5c0ec7aa-2cdd-4a32-b784-197d573f1666.jpg)
![IMG_20220802_142239](https://user-images.githubusercontent.com/105178541/183858629-d5570582-bb86-406c-a008-097a9a1a938f.jpg)

**Comment by Selah-xx** [comment]
Support page sketch
![Uploading D6820547-7F5E-4898-9C57-0F4048B59615.jpeg…]()

**Comment by Selah-xx** [comment]
Support page sketch
![D2EE9137-9667-40AE-8860-41F82ABF40F7](https://user-images.githubusercontent.com/105347907/183898489-11e8be30-eec9-4d9c-ba22-91a42a257852.jpeg)

**Comment by yinda404** [comment]
Landing page![image](https://user-images.githubusercontent.com/105176890/183929665-ff139c00-0f93-44ea-ab76-a7cd795f9bad.jpeg)

**Comment by yinda404** [comment]
About page done
![image](https://user-images.githubusercontent.com/105176890/183938254-69fc2a2b-e372-4785-bdc6-c6a47447e910.jpeg)
