### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#41]
Creating the style guide for the design process.

**Comment by SahmAdex** [comment]
- Button
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=466%3A12
- Replacement of the Spacers system
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A8


![Button System](https://user-images.githubusercontent.com/105288886/183664116-f8c8d4e6-142c-4ad1-b99c-a225cb1ce8a1.png)
![Space System](https://user-images.githubusercontent.com/105288886/183664125-65fbbc48-821c-4c07-aa55-100d1c69a5bf.png)

**Comment by FlourishRalph** [comment]
Link to the Style Guide on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=0:1

**Comment by Momohkay** [comment]
done, designed the input fields, link attached below

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A9

**Comment by Goodnesstaiwo** [comment]
spacing system designed
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A8
