### ISSUE TITLE
Web designs Wireframing

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#42]
Creating wireframes of the Landing page, Chunking pages, and the Sign up & Login pages, file authentication pages, My files & Storage pages, Recycle Bin, and Settings pages.

**Comment by FlourishRalph** [comment]
Sign Up & Log In pages - Ogheneochuko Ejeguo 
Dashboard - Catherine Ezeobi, Bamigboye Ayodeji, & Oko Ukie Emmanuel
File authentication pages - Bamigboye Ayodeji, Tobi Awokunle, Ogheneochuko Ejeguo, & Goodness Taiwo
My Files & Storage - Bamigboye Ayodeji
Settings - Tobi Awokunle
Recycle Bin - Goodness Taiwo & Ogheneochuko Ejeguo
About page - Oyindamola Dosunmu
Contact Us page - Eluyode Ifeoluwa
Support page - Catherine Ezeobi
Reset password page - Omowunmi

**Comment by FlourishRalph** [comment]
Link to the web design wireframes;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:2

**Comment by Eluyodeifeoluwa** [comment]
contact us page wirefame
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1694%3A3506

**Comment by Richochuko** [comment]
designed the login of the web wireframe

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A22

designed the signup of the web wireframe

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=501%3A12

designed the file authentication 3 of the web wireframe

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=814%3A513

designed the recycle bin of the web wireframe

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=849%3A911

**Comment by Goodnesstaiwo** [comment]
file authentication page 1
[Primary Button](https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1243%3A1502)
file authentication page 2
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2114%3A6398
file authentication page 3
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=814%3A513
recycle bin
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=849%3A911

done

**Comment by yinda404** [comment]
about page done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A2
