### ISSUE TITLE
User Research on Figjam

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#43]
Extracting information from the interviews carried out for User Research.

**Comment by FlourishRalph** [comment]
Fine tuning of the already existing User Research was carried out by Flourish Ralph & Momodu Kehinde.

The link to the FigJam board;
https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX?node-id=0:1

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX?node-id=0:1

**Comment by Richochuko** [comment]
done

https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX?node-id=0:1

**Comment by Richochuko** [comment]
worked on pain points, user persona 1 & 2, brainstorming, user story 1 & 2, and user-flow

https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX?node-id=0:1

**Comment by Neziiii** [comment]
Worked on organizing interview notes, creating empathy map, listing out user's pain points and updating the user flow.
https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX/Splita-User-Research?node-id=0%3A1
