### ISSUE TITLE
Web Low-Fi designs on Figma

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#44]
Creating the Low-Fi designs from the wireframes already on the Figma board.
The Low-Fi sketches are also used as a guide for the design implementation.

**Comment by FlourishRalph** [comment]
Sign up page - Samuel Adeyinka  & Flourish Ralph
Log In page - Eluyode Ifeoluwa & Flourish Ralph
Landing page - Eluyode Ifeoluwa & Samuel Adeyinka
Dashboard - Bamigboye Ayodeji, Flourish Ralph, & Momodu Kehinde
File authentication screens (1-3) - Samuel Adeyinka, Ogheneochuko Ejeguo, Momodu Kehinde, & Flourish Ralph.
My Files & Contact Us pages - Haruna Agnes Fatima
Storage & Reset password pages - Precious Omogoye
Recycle Bin page - Haruna Agnes Fatima & Oko Ukie Emmanuel
Settings page - Rebonye Motsweta
About page - Tobi Awokunle 
Support page - Catherine Ezeobi

**Comment by SahmAdex** [comment]
Done
Links and images are attached to this effect.

Fle Aut. 1
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=835%3A1162

File Aut. 2
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1431%3A2577

File Aut. 3
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A37
![File Authentication 1](https://user-images.githubusercontent.com/105288886/183666666-f2098873-a8b6-439f-ba48-924c2e4c2af8.png)
![File Authentication 2](https://user-images.githubusercontent.com/105288886/183666686-a1bdf1a8-7b51-4f3e-b46f-bfb3e62b71c4.png)
![File Authentication 3](https://user-images.githubusercontent.com/105288886/183666693-eb94fd06-2d15-4bb9-93ad-a5dcc8626fab.png)

**Comment by FlourishRalph** [comment]
Link to the web Low-Fi designs on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:3

**Comment by Eluyodeifeoluwa** [comment]
Done 
Links are attached below
1. sign up page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1377%3A3255
2. Landing page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1377%3A2311

**Comment by Neziiii** [comment]
Designed the web lo-fi of My files page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A35

Designed the web lo-fi of Contact us page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1698%3A3503

**Comment by Momohkay** [comment]
done, web low-fi designs, designed dashboard

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A33

**Comment by Richochuko** [comment]
designed web lo fi file authentication 3

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A37
