### ISSUE TITLE
Tweaking of the typography on the style guide

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#45]
Correcting the style guide typography.

**Comment by SahmAdex** [comment]
Done.
Link and Image are attached.

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A7
![Typography](https://user-images.githubusercontent.com/105288886/183665726-185a2ef1-79ed-467f-9dc6-3bf45a1322d7.png)

**Comment by FlourishRalph** [comment]
Link to the typography in the Style Guide page on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=0:1
