### ISSUE TITLE
Web Hi-Fi designs on Figma

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#46]
Creating the Hi-Fi designs from the Low-Fi designs already on the Figma board.

**Comment by FlourishRalph** [comment]
Sign Up page, top navigation bar for the Dashboard & Reset password page - Momodu Kehinde
Log In page, Side navigation bar for the Dashboard, & Support page - Flourish Ralph
Landing page - Oyindamola Dosunmu & Eluyode Ifeoluwa
Dashboard - Catherine Ezeobi, Momodu Kehinde, Flourish Ralph.
File authentication screens - Eluyode Ifeoluwa & Samuel Adeyinka
My File page, Storage page, & Recycle Bin page - Catherine Ezeobi
Settings page - Precious Omogoye
About page - Ogheneochuko Ejeguo
Contact Us page - Rebonye Motsweta

**Comment by SahmAdex** [comment]
Done.
Links and Images are attached to this effect.

File Aut. 3 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A45
![File Authentication 3HIFI](https://user-images.githubusercontent.com/105288886/183676062-ed493609-8450-453c-b697-ad33904345f1.png)

**Comment by FlourishRalph** [comment]
Link to the web Hi-Fi designs on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=411:4

**Comment by Eluyodeifeoluwa** [comment]
Done.
Links attached below

File Aut. 1 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=853%3A910
File Aut. 2 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=853%3A1041

**Comment by Momohkay** [comment]
done, designed dashboard

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A41

**Comment by Richochuko** [comment]
designed the about page of the web hi fi

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2078%3A6127

**Comment by yinda404** [comment]
landing page done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A4
