### ISSUE TITLE
First Presentation Preparation

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#47]
Preparing the microcopy and UI design of the presentation slides.

**Comment by FlourishRalph** [comment]
Link to the presentation design on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=835:1302

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=835:1302

**Comment by storyengineer** [comment]
Video recording.
