### ISSUE TITLE
Tidying up of the Figma board

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#48]
Tidying up of the current screens and moving to the development page.

**Comment by FlourishRalph** [comment]
Pages (Low-Fi & Hi-Fi pages) 

• Landing page
• File authentication pages (1-3)
• My files page 
• Storage page

**Comment by SahmAdex** [comment]
Done
Links are Images are attached to this effect

Landing Page Lo-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1377%3A2311
![Landing Page](https://user-images.githubusercontent.com/105288886/183668727-002138d4-6c0f-4a1f-bea5-01c77d440a6a.png)

Fle Aut. 1 Lo-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=835%3A1162
![File Authentication 1](https://user-images.githubusercontent.com/105288886/183668835-ac88248c-25d2-4937-8d99-ca807af43780.png)

File Aut. 2 Lo-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1431%3A2577
![File Authentication 2](https://user-images.githubusercontent.com/105288886/183668866-8abf8e89-3aba-4866-8c0f-e3038019dde5.png)

File Aut. 3 Lo-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A37
![File Authentication 3](https://user-images.githubusercontent.com/105288886/183668914-78ba6715-8124-4ebd-b6fa-bc73ca585191.png)

My Files Lo- Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A35

![My Files page](https://user-images.githubusercontent.com/105288886/183668984-91b47207-5fdc-4311-a292-c4719792498d.png)

My Storage Lo-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=716%3A355
![Storage](https://user-images.githubusercontent.com/105288886/183669050-8280e739-9eb1-42df-8b8a-f9b7586e4948.png)

Landing Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1286%3A1719
![Landing PageHIFI](https://user-images.githubusercontent.com/105288886/183669091-bf50505a-ce64-4389-8336-81b1eff3cf8d.png)

File Aut. 1 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=853%3A910
![File Authentication 1HIFI](https://user-images.githubusercontent.com/105288886/183669141-0d5dccca-cbd2-4918-98ca-bcca7e8bba43.png)

File Aut. 2 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=853%3A1041
![File Authentication 2HIFI](https://user-images.githubusercontent.com/105288886/183669156-17e836fb-fbb1-4b2a-85a0-2927b974a408.png)

File Aut. 3 Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A45
![File Authentication 3HIFI](https://user-images.githubusercontent.com/105288886/183669157-80e4bf27-d319-474a-9341-3d94bff78b33.png)

My Files Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1215%3A1724
![My Files pageHIFI](https://user-images.githubusercontent.com/105288886/183669240-1b79d942-7623-4846-b3fc-02ecb4b336bc.png)

My Storage Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1215%3A1968
![StorageHIFI](https://user-images.githubusercontent.com/105288886/183669290-7902ebdf-e04c-48df-b0a8-d431df6c3683.png)

**Comment by Momohkay** [comment]
done

all links have been pasted above

**Comment by Richochuko** [comment]
Done

all links to completed designs have been pasted above

**Comment by Neziiii** [comment]
Work done
Links to the figma board have been pasted above
