### ISSUE TITLE
Redesign of the Landing Page

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#49]
The landing page should be redesigned from scratch (Low-Fi & Hi-Fi) as the current one is not up to par.

**Comment by SahmAdex** [comment]
Done.
Link and image are attached.

Landing Page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1377%3A2311
![Landing Page](https://user-images.githubusercontent.com/105288886/183670797-ddcc49e5-6e63-47b9-bda7-bce0da531f2a.png)

Landing Hi-Fi
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1286%3A1719
![Landing PageHIFI](https://user-images.githubusercontent.com/105288886/183670521-13177be4-efef-4c20-b8bc-2295c68804ce.png)

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1286%3A1719

**Comment by Neziiii** [comment]
Work done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1286%3A1719
