### ISSUE TITLE
Moodboard Collation

### ISSUE THREAD

**Issue by Hydrophoenix** [zuri-training/chunkfile_team42#5]
The collation of a moodboard to help with the UI design process.

**Comment by FlourishRalph** [comment]
Links:

https://split-video.com/

https://dribbble.com/shots/18191030-In-Secure-Cloud-storage-dashboard

https://www.behance.net/gallery/83498167/CSV-File-Mockup

https://www.behance.net/gallery/136906481/File-Storage-App

https://www.behance.net/gallery/115081335/SaaS-File-Management-Dashboard

https://www.behance.net/gallery/147886331/Files-changes

https://www.behance.net/gallery/79882483/File-Upload-UI

https://extendsclass.com/csv-splitter.html

https://www.gigasheet.com/

https://www.behance.net/collection/195878929/project-chunk

https://dribbble.com/eluyodeifeoluwa/collections/5859142-project-chunk

https://www.geckoandfly.com/25051/file-joiner-splitter/

https://www.novirusthanks.org/products/file-splitter-joiner/

https://www.zamzar.com/compress/

https://www.compress2go.com/

https://peazip.github.io/file-split.html

https://www.novirusthanks.org/products/file-splitter-joiner/

**Comment by FlourishRalph** [comment]
Links to the moodboard added.

**Comment by Eluyodeifeoluwa** [comment]
Mood board collection 1
https://dribbble.com/eluyodeifeoluwa/collections/5859142-project-chunk?utm_source=Clipboard_%22clipboard_collection%22&utm_campaign=%22eluyodeifeoluwa%22&utm_content=%22project%20chunk%22&utm_medium=Social_Share
Mood board collection 2
https://www.behance.net/collection/195878929/project-chunk

**Comment by yinda404** [comment]
Moodboard collation

https://extendsclass.com/csv-splitter.html
