### ISSUE TITLE
Mobile Responsive Screens (Hi-Fi)

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#52]
Creating Hi-Fi mobile responsive screens from the Hi-Fi Web screens.

**Comment by FlourishRalph** [comment]
Landing page - Momodu Kehinde & Flourish Ralph
Sign Up & Settings pages - Goodness Taiwo
Log In & Reset Password pages - Oyindamola Dosunmu
Dashboard & Support pages - Catherine Ezeobi
File authentication 1 & Contact Us pages- Eluyode Ifeoluwa
File authentication 2 - Omowunmi 
File authentication 3 - Ogheneochuko Ejeguo
My Files page - Haruna Agnes Fatima
Storage page - Tobi Awokunle
Recycle Bin page - Precious Omogoye
About page - Haruna Agnes Fatima & Tobi Awokunle

**Comment by FlourishRalph** [comment]
Link to the Hi-Fi mobile responsive screens on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1346:4018

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1346:4018

**Comment by Eluyodeifeoluwa** [comment]
done 
links are attached below
File authentication for mobile responsiveness
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1346%3A4018
contact us page for mobile responsiveness
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2195%3A13256

**Comment by Yousuf001-ux** [comment]
Done 

Links for 'Storage page' mobile responsiveness
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1379%3A2663
and 'About page' mobile responsiveness
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2095%3A6724

**Comment by Richochuko** [comment]
designed file auth 3 for hi fi mobile responsiveness

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1620%3A3231

**Comment by yinda404** [comment]
login and reset password page done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1346%3A4018
