### ISSUE TITLE
Updating the User Flow

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#53]
Updating the user flow to fit the features we currently have in the project.

**Comment by FlourishRalph** [comment]
Link to the User flow in FigJam;
https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX?node-id=0:1

**Comment by Neziiii** [comment]
Worked with Tobi on updating the user flow
https://www.figma.com/file/kP5sRzxcf8Vw0tQde3UKEX/Splita-User-Research?node-id=0%3A1
