### ISSUE TITLE
Approving of created screens & moving for development

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#54]
Crosschecking that the created screens follow the design principles and vetting them ready for development.

**Comment by SahmAdex** [comment]
Done.
Link to the Figma attached.

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A4 (Web)
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1346%3A4018 (Mobile)

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=411%3A4
