### ISSUE TITLE
Mobile Responsive Screens (Wireframes)

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#55]
Creating Low-Fi designs for the mobile responsive screens.

**Comment by FlourishRalph** [comment]
• Sign Up & Log In pages - Goodness Taiwo
• Landing page & Dashboard - Bamigboye Ayodeji
• Recycle Bin & File authentication pages (1-3) - Samuel Adeyinka
• My files, Storage & Contact Us pages - Precious Omogoye
• About page - Haruna Agnes Fatima & Tobi Awokunle
• Support page - Rebonye Motsweta
• Reset Pssword page - Ogheneochuko Ejeguo
• Settings page - Goodness Taiwo

**Comment by SahmAdex** [comment]
Done.
Links and Images are effected to this effect.

Recycle Page
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A5012
![Recycle Bin wi-fi](https://user-images.githubusercontent.com/105288886/183671539-f4a13b77-a2ca-4d7f-afdc-117f8a1413c0.png)


File Aut. 1
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A4963
![File Authentication 1 wi-fi](https://user-images.githubusercontent.com/105288886/183671581-686bd669-794e-4c6a-84f8-565e31a057aa.png)

File Aut. 2
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A4983
![File Authentication 2 wi-fi](https://user-images.githubusercontent.com/105288886/183671619-6bc252d6-b696-4c40-998b-27f73423fea3.png)

File Aut. 3
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A5004
![File Authentication 3 wi-fi](https://user-images.githubusercontent.com/105288886/183671657-94493d54-640e-494c-9952-2f6dd7e5332a.png)

**Comment by FlourishRalph** [comment]
Link to the wireframes of the mobile responsive screens on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1965:4962

**Comment by Yousuf001-ux** [comment]
Done
The link to the 'About page' wireframe mobile responsiveness

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2084%3A6082

**Comment by Richochuko** [comment]
designed the mobile responsive screen for reset password and reset menu wireframe

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2077%3A5957

**Comment by Goodnesstaiwo** [comment]
log in page done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A5186
Sign Up page done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A5285
Settings page done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1965%3A4962
