### ISSUE TITLE
Mobile Responsive Screens (Low-Fi)

### ISSUE THREAD

**Issue by FlourishRalph** [zuri-training/chunkfile_team42#56]
Creating Low-Fi designs for the mobile responsive screens.

**Comment by FlourishRalph** [comment]
• My files page - Haruna Agnes Fatima
• Storage page - Tobi Awokunle
• File authentication screens (1-3) - Eluyode Ifeoluwa
• Recycle Bin & Dashboard - Catherine Ezeobi
• Landing page - Omowunmi 
• Sign Up, Log In & Reset Password pages - Oyindamola Dosunmu
• About page - Haruna Agnes Fatima & Tobi Awokunle
• Contact Us page - Precious Omogoye
• Support page - Rebonye Motsweta
• Settings page - Goodness Taiwo

**Comment by FlourishRalph** [comment]
Link to the Low-Fi mobile responsive screens on Figma;
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1?node-id=1885:4501

**Comment by Eluyodeifeoluwa** [comment]
mobile file authentication screen 1
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1885%3A4501
mobile file authentication screen 2
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1885%3A4501
mobile file authentication screen 3
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1885%3A4501

**Comment by Goodnesstaiwo** [comment]
settings done
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1885%3A4501

**Comment by yinda404** [comment]
sign up, login and reset password page done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=1885%3A4501
