### ISSUE TITLE
Prototyping all the Screens (WEB & MOBILE)

### ISSUE THREAD

**Issue by SahmAdex** [zuri-training/chunkfile_team42#82]

**Comment by FlourishRalph** [comment]
Link to the Prototype on Figma;
Web screens Prototype
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2243%3A6440

Mobile screens Prototype
https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2264%3A7425

**Comment by Momohkay** [comment]
done

https://www.figma.com/file/26OU2hj5mK7tlfakmOn4u1/Team-42_Chunk-file?node-id=2243%3A6440
